run:
	g++ ./src/main.cpp -o ./out/main.out && ./out/main.out data/kroA100.tsp
	python3 ./src/draw.py data/kroA100.tsp
	./out/main.out data/kroB100.tsp
	python3 ./src/draw.py data/kroB100.tsp

compile:
	g++ ./src/main.cpp -o ./out/main.out

